import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import StoreProvider from "@/store/StoreProvider";
import { AuthProvider } from "@/components/auth/AuthProvider";
import { Toaster } from "sonner";

const montserrat = Montserrat({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-montserrat",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${montserrat.variable} font-montserrat antialiased`}>
        <div>
            <StoreProvider>
              <AuthProvider>
                <Toaster/>
                <main>{children}</main>
              </AuthProvider>
            </StoreProvider>
        </div>
      </body>
    </html>
  );
}
